#include<iostream>
#include<list>
using namespace std;
class Graph
{
    int v; // No. of vertices
    list<int> *adj; // adjacency lists
    bool* visited;
public:
    Graph(){
        v=0;
        adj=NULL,visited=NULL;
    }
    Graph(int n); // Constructor
    void TakeInput(int n, int w); // to take input from the user in this sequence: number of nodes, what are the neighbors of vertex 0, what are the neighbors of vertex 1, ... so on.
    void ExploreFunction(int start); // print the paths from start to every other vertex as generated by the DFS method.One path per line.
    void Print(); //to print the DFS tree
    ~Graph(){
        delete[] adj;
        delete[] visited;
    }
};

Graph::Graph(int n){
    this->v = n;
    adj = new list<int>[v];
    visited = new bool [n];
}

void Graph::TakeInput(int n, int w){
    adj[n].push_back(w);

}

void Graph::ExploreFunction(int start){
    cout << start << " ";
    visited[start] = true;
    for(auto v:adj[start]){
        if(!visited[v])
            ExploreFunction(v);
    }
}

void Graph::Print() {
    for(int i=0;i<v;i++){
        list<int> j = adj[i];
        for(auto it:j){
            cout<<"("<<i<<","<<it<<") ";
        }
        cout<<endl;
    }
}

int main()
{
    Graph g(4); // Total 4 vertices in graph
    g.TakeInput(0, 1);
    g.TakeInput(0, 2);
    g.TakeInput(1, 2);
    g.TakeInput(2, 0);
    g.TakeInput(2, 3);
    g.TakeInput(3, 3); cout << "Following is Depth First Traversal\n";
    g.ExploreFunction(2);
//Sample output of explore function for starting from vertex 2.
//2 0
//2 0 1
//2 0 1 3
//*********
//Sample output of explore function for starting from vertex 1.
//1 2
//1 2 0
//1 2 0 3
    g.Print();
    return 0;
}